### ISSUE TITLE
Support for Stylus CSS in Grav

### ISSUE THREAD

**Issue by ganar** [getgrav/grav-plugin-scss#1]
Is there a way to install [Stylus](http://stylus-lang.com/) in Grav? I found [this library that render Stylus in PHP](https://github.com/AustP/Stylus.php). I wonder if someone can point me to a way to implement it correctly within Grav. I read the docs, but the plug in tutorial is too complex for my current knowledge of Grav, I'm also checking out this plugin and would appreciate any guidance on the process.

I need to use Stylus in order to move a project made in `roots.cx` to Grav

Many thanks

**Comment by rhukster** [comment]
Really all this plugin does is load the PHP library to make it available for other plugins. Also it provides a simple CLI command to manually compile. 

However, you don't need a plugin to use SCSS, or Stylus for that matter.  Just install stylus according to the docs: http://stylus-lang.com/#get-styling-with-stylus

And then configure it so your compiled CSS goes into css-compiled/ folder or something, and then have your theme point to that.  Sure you will have to compile offline, but this is pretty normal.  Antimatter has SCSS source files, but ships with compiled CSS files, and uses those from the theme.

**Comment by ganar** [comment]
That is a good point: I was thinking on a way to make it easier to develop the theme within Grav. 

BTW: were should I make suggestions regarding new plug-ins? you asked for them to be published in a special place that I could not find.
